name: besonc_rider
description: Besonc rider app.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  besonc_models:
    path: ../../packages/besonc_models
  besonc_ui:
    path: ../../packages/besonc_ui
  besonc_api:
    path: ../../packages/besonc_api
  besonc_auth:
    path: ../../packages/besonc_auth
  path_provider: ^2.1.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
